name: YaizuComLib Linux CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04
    timeout-minutes: 20

    steps:
    - uses: actions/checkout@v1
    - name: exec build
      run: |
        ls -l /usr/lib
        ls -l /usr/lib/x86_64-linux-gnu
        ls -l /lib64
        ls -l /usr/local/openssl
        ls -l /usr/local/openssl/lib
        cd build
        ./build.sh
    - name: exec test
      run: |
        cd build
        ./test.sh
