name: YaizuComLib Linux CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04
    timeout-minutes: 20

    steps:
    - uses: actions/checkout@v1
    - name: exec build
      run: |
        cd build
        ./build.sh
    - name: exec test
      run: |
        cd build
        ./test.sh
