name: YaizuComLib Linux CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04
    timeout-minutes: 20

    steps:
    - uses: actions/checkout@v1
    - name: exec build
      run: |
        wget https://www.openssl.org/source/openssl-1.1.1g.tar.gz
        tar -zxf openssl-1.1.1g.tar.gz
        cd openssl-1.1.1g
        ./config
        make
        sudo make install
        cd build
        ./build.sh
    - name: exec test
      run: |
        cd build
        ./test.sh
